from pathlib import Path
import numpy as np
from torch.utils.data import Dataset

class SyntheticCifar10Dataset(Dataset):
    """
    Synthetic CIFAR-10 dataset. Images are generated by passing through each image in the
    original CIFAR-10 dataset through a variational autoencoder.
    """
    def __init__(self, root):
        super().__init__()
        self.root_pth = Path(root)
        self.image_pths = self.root_pth.glob('image_*.npy')
        self.image_idxs = [int(pth.stem.split('_')[1]) for pth in self.image_pths]
        
    def __len__(self):
        return len(self.image_idxs)

    def __getitem__(self, idx):
        image = np.load(self.root_pth / self.image_pths[idx])
        with open(self.root_pth / 'label_{}.txt'.format(self.image_idxs[idx]), 'r') as f:
            label = int(f.read())
        return image, label
